<div class="page-header">
    <h1>PHP website crawler using Phalcon Framework</h1>
    <p>By <b>Neil McWilliam</b></p>
</div>

<hr>

<?php 
// Share with IndexController
$pageTitle = new IndexController; 
$responseCode = new IndexController; 
$internalLinks = new IndexController;
$externalLinks = new IndexController; 
$pageLoadTime = new IndexController; 
$uniqueImages = new IndexController; 
$wordCount = new IndexController; 

// Specify number of urls you want to crawl 
$totalUrls = 5;

// Specify the actual urls to crawl
$pageUrl1 = 'https://agencyanalytics.com/feature/seo-tools'; // seo tools page
$pageUrl2 = 'https://agencyanalytics.com/pricing'; // pricing page
$pageUrl3 = 'https://agencyanalytics.com/feature/automated-marketing-reports'; // automated marketing reports
$pageUrl4 = 'https://agencyanalytics.com/feature/white-label'; // white label
$pageUrl5 = 'https://agencyanalytics.com/feature/linkedin-dashboard'; // linkedin dashboard

// Use file_get_contents to store the page contents in variables
$pageContent1 = file_get_contents($pageUrl1); 
$pageContent2 = file_get_contents($pageUrl2); 
$pageContent3 = file_get_contents($pageUrl3); 
$pageContent4 = file_get_contents($pageUrl4); 
$pageContent5 = file_get_contents($pageUrl5); 

// Store title lengths
$titleLength1 = strlen($pageTitle->getTitle($pageUrl1));
$titleLength2 = strlen($pageTitle->getTitle($pageUrl2));
$titleLength3 = strlen($pageTitle->getTitle($pageUrl3));
$titleLength4 = strlen($pageTitle->getTitle($pageUrl4));
$titleLength5 = strlen($pageTitle->getTitle($pageUrl5));

// Calculate average title length
$averageLength = ($titleLength1 + $titleLength2 + $titleLength3 + $titleLength4 + $titleLength5) / 5;
?>

<h2>Number of pages crawled</h2>
<p><?php echo $totalUrls; ?></p>

<h2>Number of unique images</h2>
<table class="table table-bordered table-hover">
    <thead class="thead-light">
    <tr>
        <th>Page Title</th>
        <th>URL Analyzed</th>
        <th># of unique images</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl1); ?></td>
            <td><?php echo $pageUrl1; ?></td>
            <td><?php echo $uniqueImages->countUniqueImages($pageContent1); ?></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl2); ?></td>
            <td><?php echo $pageUrl2; ?></td>
            <td><?php echo $uniqueImages->countUniqueImages($pageContent2); ?></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl3); ?></td>
            <td><?php echo $pageUrl3; ?></td>
            <td><?php echo $uniqueImages->countUniqueImages($pageContent3); ?></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl4); ?></td>
            <td><?php echo $pageUrl4; ?></td>
            <td><?php echo $uniqueImages->countUniqueImages($pageContent4); ?></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl5); ?></td>
            <td><?php echo $pageUrl5; ?></td>
            <td><?php echo $uniqueImages->countUniqueImages($pageContent5); ?></td>
        </tr>
    </tbody>
</table>

<br>

<h2>Number of unique internal links</h2>
<table class="table table-bordered table-hover">
    <thead class="thead-light">
    <tr>
        <th>Page Title</th>
        <th>URL Analyzed</th>
        <th># of unique internal links</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl1); ?></td>
            <td><?php echo $pageUrl1; ?></td>
            <td><?php echo $internalLinks->countUniqueInternalLinks($pageContent1); ?></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl2); ?></td>
            <td><?php echo $pageUrl2; ?></td>
            <td><?php echo $internalLinks->countUniqueInternalLinks($pageContent2); ?></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl3); ?></td>
            <td><?php echo $pageUrl3; ?></td>
            <td><?php echo $internalLinks->countUniqueInternalLinks($pageContent3); ?></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl4); ?></td>
            <td><?php echo $pageUrl4; ?></td>
            <td><?php echo $internalLinks->countUniqueInternalLinks($pageContent4); ?></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl5); ?></td>
            <td><?php echo $pageUrl5; ?></td>
            <td><?php echo $internalLinks->countUniqueInternalLinks($pageContent5); ?></td>
        </tr>
    </tbody>
</table>

<br>

<h2>Number of unique external links</h2>
<table class="table table-bordered table-hover">
    <thead class="thead-light">
    <tr>
        <th>Page Title</th>
        <th>URL Analyzed</th>
        <th># of unique external links</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl1); ?></td>
            <td><?php echo $pageUrl1; ?></td>
            <td><?php echo $externalLinks->countUniqueExternalLinks($pageContent1); ?></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl2); ?></td>
            <td><?php echo $pageUrl2; ?></td>
            <td><?php echo $externalLinks->countUniqueExternalLinks($pageContent2); ?></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl3); ?></td>
            <td><?php echo $pageUrl3; ?></td>
            <td><?php echo $externalLinks->countUniqueExternalLinks($pageContent3); ?></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl4); ?></td>
            <td><?php echo $pageUrl4; ?></td>
            <td><?php echo $externalLinks->countUniqueExternalLinks($pageContent4); ?></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl5); ?></td>
            <td><?php echo $pageUrl5; ?></td>
            <td><?php echo $externalLinks->countUniqueExternalLinks($pageContent5); ?></td>
        </tr>
    </tbody>
</table>

<br>

<h2>Average page load</h2>
<p><b><?php echo $pageLoadTime->averagePageLoadTime(); ?> seconds</b> is the average page load time</p>

<br>

<h2>Word counts</h2>
<p>Coming soon!</p>
<!-- <p>Page 1: <?php // echo $wordCount->getWordCount($pageContent1); ?></p>
<p>Page 2: <?php // echo $wordCount->getWordCount($pageContent2); ?></p>
<p>Page 3: <?php // echo $wordCount->getWordCount($pageContent3); ?></p>
<p>Page 4: <?php // echo $wordCount->getWordCount($pageContent4); ?></p>
<p>Page 5: <?php // echo $wordCount->getWordCount($pageContent5); ?></p> -->

<br>

<h2>Average title length</h2>
<p><b><?php echo $averageLength; ?></b> characters (including spaces)</p>

<br>

<h2>Page crawled status codes</h2>
<table class="table table-bordered table-hover">
    <thead class="thead-light">
    <tr>
        <th>Page Title</th>
        <th>URL Analyzed</th>
        <th>HTTP Response Code</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl1); ?></td>
            <td><?php echo $pageUrl1; ?></td>
            <td><b><?php echo $responseCode->getResponseCode($pageUrl1); ?></b></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl2); ?></td>
            <td><?php echo $pageUrl2; ?></td>
            <td><b><?php echo $responseCode->getResponseCode($pageUrl2); ?></b></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl3); ?></td>
            <td><?php echo $pageUrl3; ?></td>
            <td><b><?php echo $responseCode->getResponseCode($pageUrl3); ?></b></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl4); ?></td>
            <td><?php echo $pageUrl4; ?></td>
            <td><b><?php echo $responseCode->getResponseCode($pageUrl4); ?></b></td>
        </tr>
        <tr>
            <td><?php echo $pageTitle->getTitle($pageUrl5); ?></td>
            <td><?php echo $pageUrl5; ?></td>
            <td><b><?php echo $responseCode->getResponseCode($pageUrl5); ?></b></td>
        </tr>
    </tbody>
</table>
